[package]
name = "starhoper"
version = "0.1.0"
edition = "2024"

[dependencies]
warp = "0.3.7"
futures = "0.3.31"
tokio = { version = "1.45.1", features = ["full"] }
tokio-tungstenite = "0.26.2"
serde_json = "1.0.140"
crossbeam = "0.8"